version: 0.2

phases:
  install:
    commands:
      - echo "Step 2 - Installing packages..."
      - apt-get update
      
  pre_build:
    commands:
      - echo "Step 2 - Getting ready..."
      - echo "Current folder is:"
      - pwd
      
  build:
    commands:
      - echo "Step 3 - Running my bash script..."
      - chmod +x ./script-2.sh
      - ./script-2.sh
      
  post_build:
    commands:
      - echo "Step 4 - All done!"